# Generated by Django 6.0 on 2026-01-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_status',
            field=models.CharField(choices=[('new', 'New'), ('code_verified', 'Code verified'), ('done', 'Done'), ('photo', 'Photo')], default='new', max_length=31),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_type',
            field=models.CharField(choices=[('via_email', 'Via Email'), ('via_phone', 'Via Phone')], max_length=31),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('ordinary_user', 'Ordinary user'), ('admin', 'Admin'), ('manager', 'Manager')], default='ordinary_user', max_length=31),
        ),
    ]
