# Generated by Django 6.0 on 2026-01-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userconfirmation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_status',
            field=models.CharField(choices=[('new', 'New'), ('code_verified', 'Code verified'), ('done', 'Done'), ('photo_done', 'Photo done')], default='new', max_length=31),
        ),
    ]
